3 integrate touchscreen calibration process
catie-aq/zephyr_zest-display-lcd_demo pull request #4
Opened 2024-10-29 15:03 UTC by andiaye33

2024-11-13 08:04 UTC, clementlgl requested changes
Can you run pre-commit on all files? The code is not properly formatted.

2024-11-13 08:04 UTC, clementlgl commented on src/main.c
> +              printk("Calibration [%d]\n", point_index);
Same, shouldn't this be displayed in a log?

2024-11-26 09:21 UTC, Sokario commented on src/main.c
> +        update_pwm();
To be resolved in issue #5.

2024-11-26 09:31 UTC, andiaye33 commented on src/main.c
> +        update_pwm();
Will be resolved in another issues

2024-11-28 09:55 UTC, andiaye33 commented
@clementlgl : this PR is ready?

2024-11-28 15:44 UTC, clementlgl requested changes

2024-11-28 15:44 UTC, clementlgl commented on prj.conf
> +CONFIG_INPUT_LOG_LEVEL_INF=y
I think this log is unnecessary

2024-11-28 15:44 UTC, clementlgl commented on src/main.c
> +					// lv_label_set_text(cross_label, "");
Clean the code

2024-11-28 15:44 UTC, clementlgl commented on src/main.c
> +#include <math.h>
All these includes are necessary? For example, I think `<zephyr/sys/printk.h>` is useless 🤔

2024-11-28 16:13 UTC, Sokario requested changes

2024-11-28 16:13 UTC, Sokario commented on prj.conf
> +CONFIG_DISPLAY_LOG_LEVEL_ERR=y
We don't need LOGs for display

2024-11-28 16:13 UTC, Sokario commented on prj.conf
> +CONFIG_LOG_DEFAULT_LEVEL=1
Can you rename it to **LEVEL_ERR** ?

2024-11-28 16:13 UTC, Sokario commented on src/main.c
> +#include <zephyr/devicetree.h>
These includes includes each other, just pick the right one

2024-12-02 07:58 UTC, clementlgl approved these changes

2024-12-05 11:00 UTC, clementlgl commented
@Sokario Can you review? It would be good to close this issue to move this example to a ‘samples’ repository.

2024-12-06 09:24 UTC, Sokario approved these changes

2024-12-06 09:24 UTC, merged